### ISSUE TITLE
sometimes when you start playing music, it does not start but is stored in a queue

### ISSUE THREAD

**Issue by maplexx14** [Resmakor/Discord-Music-Bot#2]

**Comment by Resmakor** [comment]
My queue works in such a way that when music is playing command ",play" adds music to the queue. 
This next song will not be turned on until current song finishes or after the ",skip" command. 
So this is normal behavior. The bot waits until current song finishes / is skipped, only then it turns on second song.
If this is not what you wrote about, provide more details about your problem.
![queue_working](https://user-images.githubusercontent.com/52079500/191097282-6d6b724f-ca3e-4d0e-9c1d-35ae70dbfb00.PNG)
![queue_working_2](https://user-images.githubusercontent.com/52079500/191097283-69df094e-2b61-4e09-a12a-4f91ad0a0480.PNG)

**Comment by maplexx14** [comment]
ok, thank you
